### ISSUE TITLE
@route('/view/file/<int:file_id>', methods=['GET']) generates error

### ISSUE THREAD

**Issue by xingshou** [teracyhq/flask-classful#44]
If I remove 'int:' from the route string, it works as expected, but I want to specify parameter types as  the same way flask's own route() does.
Doesn't flask-classful support argument type such as <int:file_id>? Or does it provide any other way to specify parameter types?

Sungsoo Kim

```bash
Traceback (most recent call last):
  File "manage.py", line 62, in <module>
    manager.run()
  File "/Users/sungsoo/.pyenv/versions/3.5.2/envs/cms/lib/python3.5/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/Users/sungsoo/.pyenv/versions/3.5.2/envs/cms/lib/python3.5/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/Users/sungsoo/.pyenv/versions/3.5.2/envs/cms/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 30, in list_routes
    url = url_for(rule.endpoint, **options)
  File "/Users/sungsoo/.pyenv/versions/3.5.2/envs/cms/lib/python3.5/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/Users/sungsoo/.pyenv/versions/3.5.2/envs/cms/lib/python3.5/site-packages/werkzeug/routing.py", line 1756, in build
    rv = self._partial_build(endpoint, values, method, append_unknown)
  File "/Users/sungsoo/.pyenv/versions/3.5.2/envs/cms/lib/python3.5/site-packages/werkzeug/routing.py", line 1671, in _partial_build
    append_unknown)
  File "/Users/sungsoo/.pyenv/versions/3.5.2/envs/cms/lib/python3.5/site-packages/werkzeug/routing.py", line 1679, in _partial_build
    rv = rule.build(values, append_unknown)
  File "/Users/sungsoo/.pyenv/versions/3.5.2/envs/cms/lib/python3.5/site-packages/werkzeug/routing.py", line 798, in build
    add(self._converters[data].to_url(values[data]))
  File "/Users/sungsoo/.pyenv/versions/3.5.2/envs/cms/lib/python3.5/site-packages/werkzeug/routing.py", line 1016, in to_url
    value = self.num_convert(value)
ValueError: invalid literal for int() with base 10: '[queue_id]'
```

**Comment by xingshou** [comment]
Sorry, it may not be from flask-classful. I will check-up other things and report the result.

Thanks!

**Comment by xingshou** [comment]
I have used a helper at http://flask.pocoo.org/snippets/117/ to list routes. It has a problem, not flask-classful.

Just ignore this issue!

Thanks!
